name: cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: check all files
        uses: actions/checkout@v6
      - name: set up the python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: run the cron script
        run: python hello.py