name: mail
on: push
jobs: 
  mail:
    runs-on: ubuntu-latest
    steps:
      - name: check all files
        uses: actions/checkout@v6
      - name: run the mail script
        if: ${{always()}}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
      # Optional port (defaults to 465)
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: mail title.
          body: your messages.
          to: praveena.vas2003@gmail.com
          from: praveena

        
