name: python script file
on: push
jobs: 
  mail:
    runs-on: ubuntu-latest
    steps:
      - name: check all files
        uses: actions/checkout@v6
      - name: set up the python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: run the script
        run: python hello.py
      - name: run the mail script
        if: ${{always()}}
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
      # Optional port (defaults to 465)
          port: 465
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: mail title.
          body: your messages.
          to: praveena.vas2003@gmail.com
          from: praveena

        
